name: Build & Push to ECR (debug)
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: eu-central-1
      AWS_ACCOUNT_ID: 704761460520
      ECR_REPO: helvetia-frontend
      IMAGE_TAG: v7
      IMAGE_URI: 704761460520.dkr.ecr.eu-central-1.amazonaws.com/helvetia-frontend:v7

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::704761460520:role/GitHubActions-ECRPush

      - name: Who am I (STS)
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Check ECR repo
        run: aws ecr describe-repositories --repository-names "$ECR_REPO" --region "$AWS_REGION"

      - name: Docker version
        run: docker version

      - name: Build Docker image (verbose)
        run: |
          set -eux
          docker build --pull --no-cache --progress=plain --platform linux/amd64 \
            -t "$IMAGE_URI" .

      - name: Push to Amazon ECR
        run: docker push "$IMAGE_URI"
